from .alpaca import Alpaca
from .catfish import Catfish
from .crawdad import Crawdad
from .cricket import Cricket
from .frog import Frog
from .goat import Goats
from .goldfish import Goldfish
from .leech import Leech
from .lizard import Lizard
from .ponies import Ponies
from .python import Python
from .rabbit import Rabbit
from .salamander import Salamander
from .sheep import Sheep
from .watersnake import Watersnake
from .goose import Goose
